from django.urls import path
from . import views
from django.views.generic import *

urlpatterns = [
 path("home/", views.HomeView.as_view(), name ="home"),
 path("home/<param>", views.HomeView.as_view(),name="home"),
 path("aboutUs/", views.AboutView.as_view(),name="about"),
 path("contactUs/", views.ContactView,name="contact"),
 path("produits/",views.ProduitListView.as_view(),name="lst_prdts"),
 path("produit/<pk>/" ,views.ProduitDetailView.as_view(), name="dtl_prdt"),
 path("rayons/",views.RayonListView.as_view(),name="lst_rayons"),
 path("rayon/<pk>/" ,views.RayonDetailView.as_view(), name="dtl_rayon"),
 path("categories/",views.CategorieListView.as_view(),name="lst_categories"),
 path("categorie/<pk>/" ,views.CategorieDetailView.as_view(), name="dtl_categorie"),
 path("statuts/",views.StatutListView.as_view(),name="lst_statuts"),
 path("statut/<pk>/" ,views.StatutDetailView.as_view(), name="dtl_statut"),
 path("email-sent/",views.EmailSent,name="email-sent"),
 path('login/', views.ConnectView.as_view(), name='login'),
 path('register/', views.RegisterView.as_view(), name='register'),
 path('logout/', views.DisconnectView.as_view(), name='logout'),
 path("produit/",views.ProduitCreateView.as_view(), name="crt-prdt"),
 path("produit/<pk>/update/",views.ProduitUpdateView.as_view(), name="prdt-chng"),
 path("produit/<pk>/delete/",views.ProduitDeleteView.as_view(), name="dlt-prdt"),
 path("categorie/",views.CategorieCreateView.as_view(), name="crt-categorie"),
 path("categorie/<pk>/update/",views.CategorieUpdateView.as_view(), name="categorie-chng"),
 path("categorie/<pk>/delete/",views.CategorieDeleteView.as_view(), name="dlt-categorie"),
 path("rayon/",views.RayonCreateView.as_view(), name="crt-rayon"),
 path("rayon/<pk>/update/",views.RayonUpdateView.as_view(), name="rayon-chng"),
 path("rayon/<pk>/delete/",views.RayonDeleteView.as_view(), name="dlt-rayon"),
 path("statut/",views.StatutCreateView.as_view(), name="crt-statut"),
 path("statut/<pk>/update/",views.StatutUpdateView.as_view(), name="statut-chng"),
 path("statut/<pk>/delete/",views.StatutDeleteView.as_view(), name="dlt-statut"),
 path('rayon/<pk>/cntnr', views.ContenirCreateView.as_view(), name='cntnr-crt'),
]