# Generated by Django 5.2.5 on 2025-09-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(related_name='produit', through='monApp.Contenir', to='monApp.rayon'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='produits',
            field=models.ManyToManyField(related_name='rayon', through='monApp.Contenir', to='monApp.produit'),
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='rayons',
        ),
        migrations.AddField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.produit'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='rayons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.rayon'),
        ),
    ]
