# Generated by Django 5.2.5 on 2025-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_rayons_rayon_produits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(auto_now=True),
        ),
    ]
