# Generated by Django 5.2.5 on 2025-09-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='id',
        ),
        migrations.AddField(
            model_name='contenir',
            name='pk',
            field=models.CompositePrimaryKey('produits', 'rayons', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.statut'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayons',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.rayon'),
        ),
    ]
