# Generated by Django 5.2.5 on 2025-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_remove_contenir_id_contenir_pk_produit_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='pk',
        ),
        migrations.AddField(
            model_name='contenir',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
