# Generated by Django 5.2.6 on 2025-09-25 07:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_remove_contenir_pk_contenir_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='rayons',
        ),
        migrations.AlterField(
            model_name='contenir',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_categorie', to='monApp.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.statut'),
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('produits', 'rayons')},
        ),
    ]
